management:
  endpoints:
    web:
      exposure:
        include: "prometheus"
  metrics:
    tags:
      application: ${spring.application.name}

#scrape_configs:
#  - job_name: 'spring-boot-app'
#    metrics_path: '/actuator/prometheus'
#    static_configs:
#      - targets: ['http://localhost:8080']

scrape_configs:
  - job_name: 'jobName'
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['localhost:8080']