/*
 * LOOP DFS MiniApp Microservice API
 * LOOP DFS MiniApp Microservice Documentation
 *
 * OpenAPI spec version: v0.0.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.ncba.miniapp.dto.request;


import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.ToString;

@Data
@ToString
@NoArgsConstructor
@AllArgsConstructor
public class ReverseOrderRequest {
    private String appId;
    private String orderNo;
    private String orderDate;
}
